apiVersion: v1
kind: Service
metadata:
  name: ctfd-service
spec:
  selector:
    app: ctfd
  ports:
    - name: ctfd-prot
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort

