apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: juicewatcher-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: juicewatcher
subjects:
- kind: ServiceAccount
  name: juicewatcher
  namespace: default  
