
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: juicewatcher-ingress
spec:
  rules:
  - host: juicewatcher.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
                name: juicewatcher-service
                port:
                  number: 80