apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: juicewatcher
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
