apiVersion: v1
kind: Service
metadata:
  name: juicewatcher-service
spec:
  selector:
    app: juicewatcher
  ports:
    - name: juicewatcher-prot
      protocol: TCP
      port: 80
      targetPort: 80